---
title: "Untitled"
author: "Salamone"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
eighties = read.csv('80s_alone.csv')
head(eighties)
eighties_mod = lm(horsepower ~ size, data = eighties)
summary(eighties_mod)
```

```{r}
seventies = read.csv('70s_alone.csv')
head(seventies)
seventies_mod = lm(horsepower ~ size, data = seventies)
summary(seventies_mod)
```



```{r}

seventies_mpg_mod = lm(log(horsepower) ~ highway, data = seventies)
summary(seventies_mpg_mod)

vals = runif(1000, 10, 50)

ys = predict(seventies_mpg_mod, newdata = data.frame(highway = vals))
plot(seventies$horsepower ~ seventies$highway)
par(new=TRUE)
plot(vals, exp(ys))

```

```{r}
nthroot = function(x,n) {
  (abs(x)^(1/n))*sign(x)
}

eighties_mpg_mod = lm(log(horsepower) ~   log(highway) , data = eighties)
summary(eighties_mpg_mod)

vals = runif(1000, 10, 50)

ys = predict(eighties_mpg_mod, newdata = data.frame(highway = vals))
plot(eighties$horsepower ~ eighties$highway)
par(new=TRUE)
plot(vals, exp(ys))
```




